
// This file is auto-generated by pwa_builder.py. Do not edit.
importScripts('https://storage.googleapis.com/workbox-cdn/releases/7.0.0/workbox-sw.js');

const CACHE_NAME_PREFIX = 'pwa-cachea';
const CACHE_VERSION = '1ded2d74';

if (workbox) {
    console.log(`Workbox is loaded.`);
    
    // Set up precaching for all our local files.
    // This makes the app load instantly offline.
    workbox.precaching.precacheAndRoute([
    "./",
    "Copy (2) of index.html",
    "Copy (3) of index.html",
    "Copy (4) of index.html",
    "Copy (5) of index.html",
    "Copy of Copy (5) of index.html",
    "Copy of index.html",
    "Copy of indexcl.html",
    "Copy of indexnewone.html",
    "Madrasa3.html",
    "Madrasa3_complete.js",
    "app.js",
    "app_backup/cdn.jsdelivr.net/npm/chart.js",
    "app_backup/cdnjs.cloudflare.com/ajax/libs/html2canvas/1.4.1/html2canvas.min.js",
    "app_backup/fonts.googleapis.com/css2",
    "app_backup/index.html",
    "attendance.html",
    "attendance2.html",
    "attendence and fee.html",
    "bootstrap.min.css",
    "db.js",
    "deepseek_html4.html",
    "favicon.svg",
    "firsttime.html",
    "index Yasin best till now 26-4-2025.html",
    "index.html",
    "index10 bk.html",
    "index10.html",
    "index11.html",
    "index12.html",
    "index14.html",
    "index15.html",
    "index2.html",
    "index3.html",
    "index4 copy.html",
    "index4.html",
    "index5.html",
    "index6.html",
    "index7.html",
    "index8.html",
    "index9.html",
    "index_gt.html",
    "indexcl.html",
    "indexclnew.html",
    "indexg.html",
    "indexgood.html",
    "indexgr.html",
    "indexnew.html",
    "indexnewone.html",
    "logo2.png",
    "madrasa_system_offline_copy.html",
    "madrasacln.html",
    "madrasalates.html",
    "offline.html",
    "styles.css",
    "yasin/chart.js",
    "yasin/favicon.svg",
    "yasin/html2canvas.min.js",
    "yasin/indexnewone.html",
    "yasin/jszip.min.js",
    "yasin/qrcode.min.js",
    "icon-512.png"
]);

    // Strategy for external CSS, JS libraries (e.g., from a CDN)
    // StaleWhileRevalidate: Serve from cache first (fast!), then check for updates in the background.
    workbox.routing.registerRoute(
        ({request}) => request.destination === 'script' || request.destination === 'style',
        new workbox.strategies.StaleWhileRevalidate({
            cacheName: `${CACHE_NAME_PREFIX}-external-assets-${CACHE_VERSION}`,
        })
    );
    
    // Strategy for fonts
    // CacheFirst: Once a font is downloaded, serve it from the cache forever.
    workbox.routing.registerRoute(
        ({request}) => request.destination === 'font',
        new workbox.strategies.CacheFirst({
            cacheName: `${CACHE_NAME_PREFIX}-fonts-${CACHE_VERSION}`,
            plugins: [
                new workbox.expiration.ExpirationPlugin({ maxEntries: 20, maxAgeSeconds: 365 * 24 * 60 * 60 }), // Cache for 1 year
            ],
        })
    );

    // Offline fallback for pages.
    // If you're offline and try to go to a page you've never visited, it shows offline.html
    const offlineFallback = 'offline.html';
    workbox.routing.setCatchHandler(async ({event}) => {
        if (event.request.destination === 'document') {
            return await caches.match(offlineFallback);
        }
        return Response.error();
    });

} else {
    console.log(`Workbox failed to load.`);
}
