// Auto-generated by PWA builder script.
importScripts('https://storage.googleapis.com/workbox-cdn/releases/7.0.0/workbox-sw.js');

if (workbox) {
    console.log(`Workbox is loaded.`);
    
    self.addEventListener('message', (event) => {
      if (event.data && event.data.type === 'SKIP_WAITING') {
        console.log('Service Worker received SKIP_WAITING message, activating now.');
        self.skipWaiting();
      }
    });

    workbox.precaching.precacheAndRoute([
    {
        "url": "icon-72.png",
        "revision": "d7e2fea916659bbf271b4632f028fed5"
    },
    {
        "url": "icon-96.png",
        "revision": "f1bdf68dd999551760088eb79f5cbcba"
    },
    {
        "url": "icon-128.png",
        "revision": "1ec8980d1a4a78149a5ec7aac0a52a79"
    },
    {
        "url": "icon-144.png",
        "revision": "70839b0a9ce56b64a72ca87b9c29f139"
    },
    {
        "url": "icon-152.png",
        "revision": "24fd20976f6dc6d81b99bdecd571fced"
    },
    {
        "url": "icon-192.png",
        "revision": "286958b45be08bdc916b8e3126b2203d"
    },
    {
        "url": "icon-384.png",
        "revision": "d3d46f60ff5014f7d85d047e1c55329f"
    },
    {
        "url": "icon-512.png",
        "revision": "1a98134a086859d517de611e9e0579bc"
    },
    {
        "url": "favicon.ico",
        "revision": "7cbcf8be98d3ce63133537d07504db0f"
    },
    {
        "url": ".gitignore",
        "revision": "e242b207e4ab43f11d03f1b73fbd2252"
    },
    {
        "url": "add sample data to index.html yasin best working via console.txt",
        "revision": "d3455938cd8b66c6d153e1df417d53e1"
    },
    {
        "url": "All_ID_Cards_View (1).png",
        "revision": "36e7675b4e0d78628a894b0a2b965d69"
    },
    {
        "url": "All_ID_Cards_View (2).png",
        "revision": "7e3e2a59c6002ce10ebfd4f6e7229bd1"
    },
    {
        "url": "All_ID_Cards_View.png",
        "revision": "7e3e2a59c6002ce10ebfd4f6e7229bd1"
    },
    {
        "url": "All_Result_Cards_2025-06-30.zip",
        "revision": "849bea99f53a9f303fb1af9ffef105c3"
    },
    {
        "url": "app.js",
        "revision": "0f055181425684aa95fad5ca40a064c9"
    },
    {
        "url": "attendance.html",
        "revision": "4ad3d87df8414c81722c5a9c93073db0"
    },
    {
        "url": "attendance2.html",
        "revision": "bc102af710e123e79962f8dad27678af"
    },
    {
        "url": "attendance_app.py",
        "revision": "f41b2eaff260090b9ef7ba40a36c4cc4"
    },
    {
        "url": "attendance_debug.log",
        "revision": "8d68e492f69b0f97722bae468cd85c8b"
    },
    {
        "url": "attendance_log.csv",
        "revision": "5df8153bbbf86d8ef504567d87f0d709"
    },
    {
        "url": "attendence and fee.html",
        "revision": "00b2a0b2f407a419db6b2ecda3a81ed7"
    },
    {
        "url": "attendencetable-export.pdf",
        "revision": "70dc71fd096108485a47ab440ef0647e"
    },
    {
        "url": "bgc.png",
        "revision": "36106cfb750804a9cd2d0c8633cda5ae"
    },
    {
        "url": "bgc2.png",
        "revision": "deeb0127ebbc84c22d88b3a19c732c43"
    },
    {
        "url": "bgc3.png",
        "revision": "bc3b6d222ebcb740e42f754cd3250d86"
    },
    {
        "url": "bgc4.png",
        "revision": "fbb15774e784d882a7ddbbac8ac31552"
    },
    {
        "url": "bgc5.png",
        "revision": "c98f404a5b5a2d39b9337c4ddcaaff97"
    },
    {
        "url": "bootstrap.min.css",
        "revision": "1bcf7ee45ab9975f9b9eb016fb96771a"
    },
    {
        "url": "build pwa make html app offline and installable yasin best working re-run this for updates best for html only.py",
        "revision": "912a9d55d74613b8f4f07180d0df1fd3"
    },
    {
        "url": "build pwa make html app offline and installable yasin best working.py",
        "revision": "2fc7c1c94e2f15173083ebeda834d953"
    },
    {
        "url": "Certificate-0020 (1).png",
        "revision": "b71c295d079a93dc8533555be32cea0e"
    },
    {
        "url": "Certificate-0020.png",
        "revision": "ac53e24444d5895bf27ba4c363c93610"
    },
    {
        "url": "Certificate-0094.png",
        "revision": "02ae241908699decb18f1c23ba096934"
    },
    {
        "url": "Certificate-0289 (1).png",
        "revision": "0f83e810a7dcf36366a8fc97e71eb7d0"
    },
    {
        "url": "Certificate-0289 (2).png",
        "revision": "1fe2706643269e42f959a4e294c845ee"
    },
    {
        "url": "Certificate-0289.png",
        "revision": "f9d30c45f257d15c5609b0fa08cd588d"
    },
    {
        "url": "Certificate_Ahmed_Ali.png",
        "revision": "683618075699fbcb898792756632f39d"
    },
    {
        "url": "Certificate_\u0628\u0644\u0627\u0644.png",
        "revision": "791531e8e6381017186306a2143e566c"
    },
    {
        "url": "client messagae for the madrasa system.txt",
        "revision": "c358ec94d3a2285afea4d78438f9912a"
    },
    {
        "url": "Copy (2) of index.html",
        "revision": "8c855a60a07883d885f68b5d3b06903d"
    },
    {
        "url": "Copy (3) of index.html",
        "revision": "f46f3ffa22cdc90c1bbd1c03fa941ee9"
    },
    {
        "url": "Copy (4) of index.html",
        "revision": "eecf8086d931f92907d55dbcebc2b1d4"
    },
    {
        "url": "Copy (5) of index.html",
        "revision": "f4ba4771f09a25d5fcae3360a300f534"
    },
    {
        "url": "Copy of Copy (5) of index.html",
        "revision": "ee9afe29d9f512638529fca06e11700f"
    },
    {
        "url": "Copy of index.html",
        "revision": "e23b5253e9572e7ad97c275906467603"
    },
    {
        "url": "Copy of indexcl.html",
        "revision": "3436b760eaaa5052e1631a19506c0c7e"
    },
    {
        "url": "Copy of indexcl.txt",
        "revision": "926bafedd7c8b4a6580abfc631580ded"
    },
    {
        "url": "Copy of indexnewone.html",
        "revision": "148c1173139a0f5d1b515cc4366eb095"
    },
    {
        "url": "Copy of phpmadrasa.txt",
        "revision": "b4fd811f8c95bd518bdc583c0537e70c"
    },
    {
        "url": "Copy of schoolnewone.php",
        "revision": "4cec8d3bf24a26deb5f61243afad0425"
    },
    {
        "url": "create users via console yasin indexnewone.html.txt",
        "revision": "0db051dc0ab8c8c98157ef3d80994228"
    },
    {
        "url": "data5 newa.csv",
        "revision": "fe002df568772423dbc09e70254fc544"
    },
    {
        "url": "db.js",
        "revision": "be291f33dcce75e9f3049cb03680ec19"
    },
    {
        "url": "events-table-export.pdf",
        "revision": "237fa991ad431fac196ef67b0f7bf9e1"
    },
    {
        "url": "favicon (1).ico",
        "revision": "f79f8475937b74fbd5ceebe0a998fa34"
    },
    {
        "url": "favicon.svg",
        "revision": "66bdb64e49e91dcf91a5742fbf7cb176"
    },
    {
        "url": "firsttime.html",
        "revision": "5c7adf8dfc5828644671db813fa5a46e"
    },
    {
        "url": "get ready id cards for printing in pdf for indexnewone.html.py",
        "revision": "b78f5591a727c0101748161738dc1054"
    },
    {
        "url": "give admin login id card and certificate permission via console for indexnewone.html.txt",
        "revision": "6a0c3f93e9c97989d20bc89234ed8f7c"
    },
    {
        "url": "gschool app.exe",
        "revision": "299bc6e82d97baf239d7b9de7188a018"
    },
    {
        "url": "html14.html",
        "revision": "f04835b400f1c2f30c33fd614e5e6ff0"
    },
    {
        "url": "id card and certificate.html",
        "revision": "f49fc931f53be1b28a90072239ced4d2"
    },
    {
        "url": "ID-Card-0002-Back.png",
        "revision": "be926cdcfecb019eacfe104fea8f203f"
    },
    {
        "url": "ID-Card-0002-Front (1).png",
        "revision": "bc2081ac645c2405e62ee34f2ce504ce"
    },
    {
        "url": "ID-Card-0002-Front.png",
        "revision": "da3cfe004c189083f4bc92f05fea4e70"
    },
    {
        "url": "ID-Card-0062-Front.png",
        "revision": "dc18e95eb77c5b682dc8ed7229e84209"
    },
    {
        "url": "id-card-Rajesh-Gupta (1).png",
        "revision": "f8a3d8a4a620c78935eb033163b278cb"
    },
    {
        "url": "id-card-Rajesh-Gupta.png",
        "revision": "f8a3d8a4a620c78935eb033163b278cb"
    },
    {
        "url": "id-card-Sita-Devi.png",
        "revision": "dcfa236cef3b12e0a3e3eddfaa2d3ebd"
    },
    {
        "url": "index Yasin best till now 26-4-2025.html",
        "revision": "4a45913d2359f9092df3b0012771b67e"
    },
    {
        "url": "index.html",
        "revision": "44fc6ef727740647a728372dbfcddf72"
    },
    {
        "url": "index10 bk.html",
        "revision": "cdc74fe83fe40814c41d2bda97abc2dd"
    },
    {
        "url": "index10.html",
        "revision": "07c56b76d07bedb229e863d671059fb8"
    },
    {
        "url": "index11.html",
        "revision": "c8b473a0a954cc320dcae98dd38658cc"
    },
    {
        "url": "index12.html",
        "revision": "08846eb93e97a7166c0a44cbac2cc395"
    },
    {
        "url": "index14.html",
        "revision": "82893031c4441566291e9a6e9e6e4990"
    },
    {
        "url": "index15.html",
        "revision": "11be3c118a7dd47fbc55f93a1d126b75"
    },
    {
        "url": "index2.html",
        "revision": "d5f463cbc9af4423f777fbd7cc58bfac"
    },
    {
        "url": "index3.html",
        "revision": "31cf4a5d3399288a7c5f67f64682fc3f"
    },
    {
        "url": "index4 copy.html",
        "revision": "b9928f59b44b3bb36fe937d3678753e1"
    },
    {
        "url": "index4.html",
        "revision": "80fa8e38c8818c7478eb3a4fc08bb463"
    },
    {
        "url": "index5.html",
        "revision": "043448ff384f2e14bc54109b20e2c474"
    },
    {
        "url": "index6.html",
        "revision": "e554b69e9765d88faa6e6a0aa9d84181"
    },
    {
        "url": "index7.html",
        "revision": "dda9237960c90bf552166ec4c7a32967"
    },
    {
        "url": "index8.html",
        "revision": "7459c5064a9f072299874c171bb5b067"
    },
    {
        "url": "index9.html",
        "revision": "ae00730c200997660b10098c1caa28c5"
    },
    {
        "url": "indexcl.html",
        "revision": "0ff7356388fe308361fd9d59ee5f3428"
    },
    {
        "url": "indexclnew.html",
        "revision": "fbd49b5f4796929dec53dcfe94bf9248"
    },
    {
        "url": "indexg.html",
        "revision": "e47463b876ddb7bcdac522e908da43bf"
    },
    {
        "url": "indexg.txt",
        "revision": "201760190bfc8d2b3d2d7eeb05f164d9"
    },
    {
        "url": "indexgood.html",
        "revision": "5a61256ba0701cb0af4e5c6c996cac8f"
    },
    {
        "url": "indexgr.html",
        "revision": "b6d741e1feee534803e0ac5d3c55c561"
    },
    {
        "url": "indexnew.html",
        "revision": "8b2ba54f9b6173d3415778deb250a600"
    },
    {
        "url": "indexnewone readme file guide full.pdf",
        "revision": "1dbfb01b7e8f12ae66a5318d66ef10a1"
    },
    {
        "url": "indexnewone readme file guide shortcut keys.pdf",
        "revision": "45d0a1e954a8a53777928b38f7de1190"
    },
    {
        "url": "indexnewone readme file guide.docx",
        "revision": "2761387d597a9a8632fda14cfa0d760b"
    },
    {
        "url": "indexnewone readme file guide.pdf",
        "revision": "bc72f9342e38411dba062d1923f3de5b"
    },
    {
        "url": "indexnewone.html",
        "revision": "9db8f2e3f1dac951fa7d91c4ff0395a8"
    },
    {
        "url": "indexnewonemakeacopy.py",
        "revision": "e707e140f7a8d76b8f52a7cf8a3924ec"
    },
    {
        "url": "indexnewonexact.php",
        "revision": "f8d63bdea0c054fb0e85c81a0effa43f"
    },
    {
        "url": "index_gt.html",
        "revision": "c4bf0f3216a42d6bc7590c3d387820dc"
    },
    {
        "url": "js code for adding sample data to my madrasa index.html.txt",
        "revision": "009c26abb226b5d0787736c329d7d565"
    },
    {
        "url": "log.jpeg",
        "revision": "f588eee480fef3d27e82658d488d5365"
    },
    {
        "url": "login system js code for indexnewone.html js obfuscated yasin.txt",
        "revision": "06e513a4ad35d89ea004ad026c16ffe9"
    },
    {
        "url": "logo.png",
        "revision": "d9c1a142d15554d4de4c82d5ef7ee647"
    },
    {
        "url": "logo2.png",
        "revision": "d93cb2d5fb11ecb269be932f0e96def4"
    },
    {
        "url": "logoe.png",
        "revision": "ce3a80426537a6185191a0c2118aa80a"
    },
    {
        "url": "madrasa.sqlite",
        "revision": "d60365565e85d7567854d079d260dc58"
    },
    {
        "url": "Madrasa3.html",
        "revision": "79030024d450b9736f13fe2c2ef670fb"
    },
    {
        "url": "Madrasa3_complete.js",
        "revision": "8cbb41b181df8eb082d0b6bfb66cc410"
    },
    {
        "url": "madrasacln.html",
        "revision": "4c5e0382e1239541cfebb8e39e45f6fc"
    },
    {
        "url": "madrasalates.html",
        "revision": "7807ee43223424cd85b9197bd903cbf1"
    },
    {
        "url": "madrasa_system_offline_copy.html",
        "revision": "fa04ba5e15b1704e0c097fcff2cb843d"
    },
    {
        "url": "makeitoffline.py",
        "revision": "401dff581a3537b6ca0075aefd234e76"
    },
    {
        "url": "manifest.json",
        "revision": "0633c88fb2a564a85d36a487d8d12f5b"
    },
    {
        "url": "newlog.png",
        "revision": "1ff3994e77d3f8932391e0ba8710131d"
    },
    {
        "url": "newlog2.png",
        "revision": "b5fdca6616df166ee55e1fa8d91f47e0"
    },
    {
        "url": "newlogo.svg",
        "revision": "66bdb64e49e91dcf91a5742fbf7cb176"
    },
    {
        "url": "offline.html",
        "revision": "800700bd3997c93b24697caef58542f0"
    },
    {
        "url": "phpmadrasa.php",
        "revision": "1f5adb316c5f1d50f502c99c6ce1aeff"
    },
    {
        "url": "readme file for schoolnewone.pdf",
        "revision": "7c1a4652079d7f6912d9b9c01c387376"
    },
    {
        "url": "readme file for schoolnewone.php.docx",
        "revision": "faeddb175c723733eedaebc15b709705"
    },
    {
        "url": "README.md",
        "revision": "a7eb8ca8793c9d19cb7948b3f45670fb"
    },
    {
        "url": "SalarySlip-T001-January.png",
        "revision": "17ac1e810951e6ab5a37d821537c944e"
    },
    {
        "url": "SalarySlip_\u0627\u0633\u0627\u0645\u06c1_\u0628\u0646_\u06cc\u0627\u0633\u0631_2025-06-29 (1).png",
        "revision": "5c576a662a2ca06864f2d922f5b73583"
    },
    {
        "url": "SalarySlip_\u0627\u0633\u0627\u0645\u06c1_\u0628\u0646_\u06cc\u0627\u0633\u0631_2025-06-29.png",
        "revision": "c5884dc86e02f29f7269d6a95e25d7d2"
    },
    {
        "url": "sample data for index.html yasin latest 29-6-2025.txt",
        "revision": "915bcbca41e7443b36aabad4222d3a3e"
    },
    {
        "url": "school app yasin best.html",
        "revision": "1c9d477c1dbf1869fef8cea799bb6c43"
    },
    {
        "url": "school app.ahk",
        "revision": "24fe5c86a37e3a66a17e844b74ca73c7"
    },
    {
        "url": "school app.exe",
        "revision": "ee543c7a507f129c069ca65f3c7cf95c"
    },
    {
        "url": "school.png",
        "revision": "db98c13fbc2d0e38dd1eaa664a37c8c2"
    },
    {
        "url": "school.py",
        "revision": "8b3e2f684de99a8595a5421891e81ad9"
    },
    {
        "url": "school2.py",
        "revision": "90ccab0f3fe677da8df23928994d32a8"
    },
    {
        "url": "schoolnewone.php",
        "revision": "b24e1d02273fb1cedd0f9f5330af0c83"
    },
    {
        "url": "school_madrasa.db",
        "revision": "257281cf740349ec0bfb63ff105112ad"
    },
    {
        "url": "school_madrasa_backup_20250630_163701.db",
        "revision": "98da4e437bc3b0b60e09fa5ba102d0fe"
    },
    {
        "url": "school_madrasa_backup_full_2025-08-20_10-25-01.sql",
        "revision": "aa280946bb9027120f750cc44d50b53f"
    },
    {
        "url": "school_madrasa_dba-db_2025-08-20 db backup for indexnewoneexact.php.sql",
        "revision": "a100333dc3abef72742dcbf85d0804fd"
    },
    {
        "url": "school_management.db",
        "revision": "68580baa5c607176c458709fad9fe671"
    },
    {
        "url": "school_management_db-db_2025-08-19 for schoolnewone.php.sql",
        "revision": "9d8f67a938e7cb7cacd1a78d2f0d565f"
    },
    {
        "url": "school_management_dbv2-db_2025-08-29 for schoolnewone.php.sql",
        "revision": "02251c4884207bbc1c62416c6665d5c6"
    },
    {
        "url": "script for inexnewone.html for disabling inspect and other things for security.txt",
        "revision": "15543ca48968f33980656e7031d8acf3"
    },
    {
        "url": "sign.png",
        "revision": "942385e276d966653100af1abf9dd728"
    },
    {
        "url": "sqlite.php",
        "revision": "a14cf14abc8ddb48be4f0cc64e9fc82b"
    },
    {
        "url": "student-due-fees-table-export.pdf",
        "revision": "011e27f64c36a91b9d9b4bb16215059d"
    },
    {
        "url": "students_data.csv",
        "revision": "fe6e174a4db8a056857fd4a620b54c62"
    },
    {
        "url": "styles.css",
        "revision": "5f49f85f9aa964f41db09740b1a6ae40"
    },
    {
        "url": "sw.js",
        "revision": "3830edd20cb57f9598ef9c5330c649fa"
    },
    {
        "url": "table-export attendence.pdf",
        "revision": "fbcfae5a9ea55f10ab12fda499e911f8"
    },
    {
        "url": "table-export.pdf",
        "revision": "f2eb0eb12f3ca5121136bcb8ed8248e4"
    },
    {
        "url": "table_export_1751109827293.pdf",
        "revision": "c0803a37be0d248e47c67601daa95cca"
    },
    {
        "url": "to eng.py",
        "revision": "2830e0daf5732e466af7bbd3acb4789a"
    },
    {
        "url": "yasin_futuristic_logo.svg",
        "revision": "4087fad3a96adb5fc50c2ab0addf18f0"
    },
    {
        "url": "Yasin_Ullah_back (1).png",
        "revision": "6d3fd90cc95f2a4999bdf07c91cd1420"
    },
    {
        "url": "Yasin_Ullah_front.png",
        "revision": "6fddfeeaa3fd53405df5c32bae1b6783"
    },
    {
        "url": "All_Result_Cards_2025-06-30/ResultCard_0031_Rukhsana_Sheikh.png",
        "revision": "49c0f676551480cc96eaa5e975833bb8"
    },
    {
        "url": "All_Result_Cards_2025-06-30/ResultCard_0032_Imran_Naqvi.png",
        "revision": "905ed7e4cae4e0e5170a3287f334288e"
    },
    {
        "url": "All_Result_Cards_2025-06-30/ResultCard_0033_Ahmad_Usmani.png",
        "revision": "abca214ef9f7130ddf8cbfab2263dbe5"
    },
    {
        "url": "All_Result_Cards_2025-06-30/ResultCard_0034_Maryam_Sheikh.png",
        "revision": "021e1d456c94de920551bb4675bbadf7"
    },
    {
        "url": "All_Result_Cards_2025-06-30/ResultCard_0035_Ali_Naqvi.png",
        "revision": "3d9978e6313cd6a6b2312c27bddee6d0"
    },
    {
        "url": "All_Result_Cards_2025-06-30/ResultCard_0036_Imran_Abbasi.png",
        "revision": "046c7cb12b246ca22a7d31142551800b"
    },
    {
        "url": "All_Result_Cards_2025-06-30/ResultCard_0037_Salma_Naqvi.png",
        "revision": "8b64332d0d0587c769e76684f8fed9e2"
    },
    {
        "url": "All_Result_Cards_2025-06-30/ResultCard_0038_Tariq_Siddiqui.png",
        "revision": "4410f98661f8f68b6125ade1facad6fe"
    },
    {
        "url": "All_Result_Cards_2025-06-30/ResultCard_0039_Faisal_Usmani.png",
        "revision": "12144264643cb395ba23af944ddf6a1c"
    },
    {
        "url": "All_Result_Cards_2025-06-30/ResultCard_0040_Khadijah_Syed.png",
        "revision": "a7c5f13bb79e0e944eff0270a96a6c99"
    },
    {
        "url": "app_backup/bgc.png",
        "revision": "36106cfb750804a9cd2d0c8633cda5ae"
    },
    {
        "url": "app_backup/index.html",
        "revision": "1090fd44246684d66b31405c1979a42c"
    },
    {
        "url": "app_backup/logo2.png",
        "revision": "d93cb2d5fb11ecb269be932f0e96def4"
    },
    {
        "url": "app_backup/cdn.jsdelivr.net/npm/chart.js",
        "revision": "187ffe7a12d1079ea1653198f9e19187"
    },
    {
        "url": "app_backup/cdnjs.cloudflare.com/ajax/libs/html2canvas/1.4.1/html2canvas.min.js",
        "revision": "d7530aa0b7587e627484c49fdf8f13f2"
    },
    {
        "url": "app_backup/fonts.googleapis.com/css2",
        "revision": "3cd6b6b471ac0f52c05df1c640cb6cdd"
    },
    {
        "url": "backups/school_madrasa_backup_full_2025-08-20_10-25-01.sql",
        "revision": "aa280946bb9027120f750cc44d50b53f"
    },
    {
        "url": "client_pics/students_68a5ac16cc2d17.21712132.jpeg",
        "revision": "1cc33aef68353599cfd5281f6ad28164"
    },
    {
        "url": "Generated_ID_Cards_2025-06-27/0001_Rabia_Ansari_Back.png",
        "revision": "7e4fcced59a24b25aec043be5335ddc0"
    },
    {
        "url": "Generated_ID_Cards_2025-06-27/0001_Rabia_Ansari_Front.png",
        "revision": "bb73543e67c3c838dfc257d436afb867"
    },
    {
        "url": "Generated_ID_Cards_2025-06-27/0002_Hassan_Gilani_Back.png",
        "revision": "3b6db01112d40f990a88adb3ebd9c2fd"
    },
    {
        "url": "Generated_ID_Cards_2025-06-27/0002_Hassan_Gilani_Front.png",
        "revision": "6bc1a4f3655f5b4d04e4fd3144843ea3"
    },
    {
        "url": "Generated_ID_Cards_2025-06-27/0003_Nashwa_Ejaz_Back.png",
        "revision": "5c8da20933ef564b216df790e478ee97"
    },
    {
        "url": "Generated_ID_Cards_2025-06-27/0003_Nashwa_Ejaz_Front.png",
        "revision": "458e08cc66c840511685c6646fec4500"
    },
    {
        "url": "Generated_ID_Cards_2025-06-27/0004_Khadijah_Mahmood_Back.png",
        "revision": "4ee4e210501667d51881c6123d67d559"
    },
    {
        "url": "Generated_ID_Cards_2025-06-27/0004_Khadijah_Mahmood_Front.png",
        "revision": "999cf35f1213065c0c3258f1471b64c6"
    },
    {
        "url": "Generated_ID_Cards_2025-06-27/0005_Maryam_Razvi_Back.png",
        "revision": "e337254f0d29d70ac30587ceb92c842d"
    },
    {
        "url": "Generated_ID_Cards_2025-06-27/0005_Maryam_Razvi_Front.png",
        "revision": "25f48cd64638d4d160c7f57b11b49fbb"
    },
    {
        "url": "Generated_ID_Cards_2025-06-27/0006_Saba_Gilani_Back.png",
        "revision": "33dd642b531ba4fc87a1163591368df7"
    },
    {
        "url": "Generated_ID_Cards_2025-06-27/0006_Saba_Gilani_Front.png",
        "revision": "3d2c599764e96aca0dbb07a5df64c63e"
    },
    {
        "url": "Generated_ID_Cards_2025-06-27/0007_Usman_Gilani_Back.png",
        "revision": "51d8d910047bbfe02bcd61e378147c9b"
    },
    {
        "url": "Generated_ID_Cards_2025-06-27/0007_Usman_Gilani_Front.png",
        "revision": "5ff9e9ba26a18593064f47e251ff6c5d"
    },
    {
        "url": "Generated_ID_Cards_2025-06-27/0008_Safia_Bukhari_Back.png",
        "revision": "587f686640c9f74be4b08b82aef58446"
    },
    {
        "url": "Generated_ID_Cards_2025-06-27/0008_Safia_Bukhari_Front.png",
        "revision": "1a24180a34190d6ec20b19ee9aeebb13"
    },
    {
        "url": "Generated_ID_Cards_2025-06-27/0009_Hussein_Hashmi_Back.png",
        "revision": "e0585743f46febe6dc0aa9079068d69a"
    },
    {
        "url": "Generated_ID_Cards_2025-06-27/0009_Hussein_Hashmi_Front.png",
        "revision": "7c07c90659a47fb243349fe41d1c6197"
    },
    {
        "url": "Generated_ID_Cards_2025-06-27/0010_Safia_Bukhari_Back.png",
        "revision": "d2505ee78b55d72757968b0d58877835"
    },
    {
        "url": "Generated_ID_Cards_2025-06-27/0010_Safia_Bukhari_Front.png",
        "revision": "97f623fc115273621d506ede8f924152"
    },
    {
        "url": "Generated_ID_Cards_2025-06-27/0011_Abdul_Rahman_Bukhari_Back.png",
        "revision": "6b18ef175075e3a77d830f68d3746bdf"
    },
    {
        "url": "Generated_ID_Cards_2025-06-27/0011_Abdul_Rahman_Bukhari_Front.png",
        "revision": "002da2e7558a4b1c48993c9efd179e5f"
    },
    {
        "url": "Generated_ID_Cards_2025-06-27/0012_Bilal_Siddiqui_Back.png",
        "revision": "68645959d644f56b441920abfe94f18e"
    },
    {
        "url": "Generated_ID_Cards_2025-06-27/0012_Bilal_Siddiqui_Front.png",
        "revision": "d2333d126c7010accef4f933a262faf9"
    },
    {
        "url": "Generated_ID_Cards_2025-06-27/0013_Nashwa_Siddiqui_Back.png",
        "revision": "b36fdee084a2f0737d7a2f27dad9558e"
    },
    {
        "url": "Generated_ID_Cards_2025-06-27/0013_Nashwa_Siddiqui_Front.png",
        "revision": "edc6ef8f2a333b316d3cc616fe162b5c"
    },
    {
        "url": "Generated_ID_Cards_2025-06-27/0014_Rabia_Naqvi_Back.png",
        "revision": "d596a403324830b18620bad2197d0d1f"
    },
    {
        "url": "Generated_ID_Cards_2025-06-27/0014_Rabia_Naqvi_Front.png",
        "revision": "73fe68c86fb664b5da8e55a175f4f058"
    },
    {
        "url": "Generated_ID_Cards_2025-06-27/0015_Maryam_Farooqi_Back.png",
        "revision": "2412fdbf2eaea8cc8c29826b9f6f2026"
    },
    {
        "url": "Generated_ID_Cards_2025-06-27/0015_Maryam_Farooqi_Front.png",
        "revision": "8187a1c359358af0da9f7c989f7813ae"
    },
    {
        "url": "Generated_ID_Cards_2025-06-27/0016_Ahmad_Farooqi_Back.png",
        "revision": "572e2f7b9d6669dd3993e62427b7827a"
    },
    {
        "url": "Generated_ID_Cards_2025-06-27/0016_Ahmad_Farooqi_Front.png",
        "revision": "9325ebdbfaffa9d2c18e9114b71f530f"
    },
    {
        "url": "Generated_ID_Cards_2025-06-27/0017_Abdul_Rahman_Khan_Back.png",
        "revision": "2b7b1cb296028e2bd7a583539aa23bcf"
    },
    {
        "url": "Generated_ID_Cards_2025-06-27/0017_Abdul_Rahman_Khan_Front.png",
        "revision": "ea762426cd091d02c40842c27697dd55"
    },
    {
        "url": "Generated_ID_Cards_2025-06-27/0018_Safia_Khan_Back.png",
        "revision": "c27d2f841643667bf957b15ce162c8cc"
    },
    {
        "url": "Generated_ID_Cards_2025-06-27/0018_Safia_Khan_Front.png",
        "revision": "5e0db820b1c51b830fa51e49517eb30c"
    },
    {
        "url": "Generated_ID_Cards_2025-06-27/0019_Waseem_Ansari_Back.png",
        "revision": "1c67d12b83fa7788fda468be8c6f82f3"
    },
    {
        "url": "Generated_ID_Cards_2025-06-27/0019_Waseem_Ansari_Front.png",
        "revision": "2c91a1ea99ff1080fbe70a8fbe2064e6"
    },
    {
        "url": "Generated_ID_Cards_2025-06-27/0020_Shabnam_Hashmi_Back.png",
        "revision": "563310b61080e21beae3faebc5dd2857"
    },
    {
        "url": "Generated_ID_Cards_2025-06-27/0020_Shabnam_Hashmi_Front.png",
        "revision": "a230c009053fdd426c64ae6ffe9dd99c"
    },
    {
        "url": "Generated_ID_Cards_2025-06-27/0021_Afia_Syed_Back.png",
        "revision": "962f7e32a2b40420df0e6867ffe3d729"
    },
    {
        "url": "Generated_ID_Cards_2025-06-27/0021_Afia_Syed_Front.png",
        "revision": "63c6f8ffa779d7604009e4d8b2fbf0da"
    },
    {
        "url": "Generated_ID_Cards_2025-06-27/0022_Hafsa_Ejaz_Back.png",
        "revision": "680365bf4ded0b4c6b468db168da6a65"
    },
    {
        "url": "Generated_ID_Cards_2025-06-27/0022_Hafsa_Ejaz_Front.png",
        "revision": "39b87b5526b0101d0ebccb55d3299077"
    },
    {
        "url": "Generated_ID_Cards_2025-06-27/0023_Akram_Razvi_Back.png",
        "revision": "6d90307c1b968eccce4eb34c68a570b5"
    },
    {
        "url": "Generated_ID_Cards_2025-06-27/0023_Akram_Razvi_Front.png",
        "revision": "a09d9cdb133860abb42053f85537813a"
    },
    {
        "url": "Generated_ID_Cards_2025-06-27/0024_Khadijah_Ejaz_Back.png",
        "revision": "48c2a90e95a46a4c90ef3079af2a0422"
    },
    {
        "url": "Generated_ID_Cards_2025-06-27/0024_Khadijah_Ejaz_Front.png",
        "revision": "eb701b42753c720cb0595047b56bb918"
    },
    {
        "url": "Generated_ID_Cards_2025-06-27/0025_Ibrahim_Ansari_Back.png",
        "revision": "4d6c85e1476b607421ab332404b6aa53"
    },
    {
        "url": "Generated_ID_Cards_2025-06-27/0025_Ibrahim_Ansari_Front.png",
        "revision": "c125ccb7b3f4a061df715e98de5cdeca"
    },
    {
        "url": "Generated_ID_Cards_2025-06-27/0026_Zainab_Naqvi_Back.png",
        "revision": "ab612d7cbe75e488eebb457c0da1c4b2"
    },
    {
        "url": "Generated_ID_Cards_2025-06-27/0026_Zainab_Naqvi_Front.png",
        "revision": "993b06c5dc1ed1cd962350c85443b86c"
    },
    {
        "url": "Generated_ID_Cards_2025-06-27/0027_Ismail_Chaudhry_Back.png",
        "revision": "44d3a6df381a43f03ce3f9983e79d50f"
    },
    {
        "url": "Generated_ID_Cards_2025-06-27/0027_Ismail_Chaudhry_Front.png",
        "revision": "951f2c13f92c1ee649c396d4fafd9ca9"
    },
    {
        "url": "Generated_ID_Cards_2025-06-27/0028_Aminah_Khan_Back.png",
        "revision": "71de8120a6a7ed12303228539cc8f1bd"
    },
    {
        "url": "Generated_ID_Cards_2025-06-27/0028_Aminah_Khan_Front.png",
        "revision": "c48c3a03de644777861a26cd1f1c2439"
    },
    {
        "url": "Generated_ID_Cards_2025-06-27/0029_Zainab_Alam_Back.png",
        "revision": "322367b6c7f09bb647477b1f391326b1"
    },
    {
        "url": "Generated_ID_Cards_2025-06-27/0029_Zainab_Alam_Front.png",
        "revision": "1e23e65b44c29c3e9c55f7a96bf89cf6"
    },
    {
        "url": "Generated_ID_Cards_2025-06-27/0030_Waseem_Sheikh_Back.png",
        "revision": "ade047f76637f5d958825b0f61d13570"
    },
    {
        "url": "Generated_ID_Cards_2025-06-27/0030_Waseem_Sheikh_Front.png",
        "revision": "1742a9cbb6db717ebb2f02beefd8efd6"
    },
    {
        "url": "Generated_ID_Cards_2025-06-27/Ayah_1_1.png",
        "revision": "67e49cb57b1ae991b5b553d53ab99256"
    },
    {
        "url": "Generated_ID_Cards_2025-06-27/Certificate-0181.png",
        "revision": "cc2571e38990132f636a2fe9a0e240ae"
    },
    {
        "url": "Generated_ID_Cards_2025-06-27/Certificate_\u0628\u0644\u0627\u0644_\u0635\u062f\u06cc\u0642\u06cc.png",
        "revision": "d89b2bfefcde24631f654b7353c0ab41"
    },
    {
        "url": "Generated_ID_Cards_2025-06-27/Custom_Certificates_1751033295053.zip",
        "revision": "5d6f34273e37dc44cd96008b3bf619d7"
    },
    {
        "url": "Generated_ID_Cards_2025-06-27/Custom_Certificates_1751033615274.zip",
        "revision": "2cfa2a41cf030a11a37de4b84ac45911"
    },
    {
        "url": "Generated_ID_Cards_2025-06-27/get ready id cards for printing in pdf for indexnewone.html.py",
        "revision": "b78f5591a727c0101748161738dc1054"
    },
    {
        "url": "Generated_ID_Cards_2025-06-27/id_cards_for_print.pdf",
        "revision": "b7dbec4be8526834a7d13d86219bc127"
    },
    {
        "url": "Generated_ID_Cards_2025-06-27/id_card_1751096841999.png",
        "revision": "aac3423bbe97f112405bff8f8325916c"
    },
    {
        "url": "Generated_ID_Cards_2025-06-27/yasin.png",
        "revision": "3561dc6e17920f802981788bc2bd22bc"
    },
    {
        "url": "Generated_ID_Cards_2025-06-27/\u0627\u0633\u0627\u0645\u06c1_\u0628\u0646_\u0632\u06cc\u062f.png",
        "revision": "d5264b1cf42b4a1f4ae4c16b6de8c0c7"
    },
    {
        "url": "Generated_ID_Cards_2025-06-27/\u062d\u0641\u0635\u06c1_\u0628\u06cc_\u0628\u06cc.png",
        "revision": "e15170b96eb86690217970605a5d9c05"
    },
    {
        "url": "images/ADM0541101.png",
        "revision": "2499e0fda40d2282524ddcade1625c8a"
    },
    {
        "url": "images/logo.png",
        "revision": "d9c1a142d15554d4de4c82d5ef7ee647"
    },
    {
        "url": "images/\u0627\u0646\u0633.png",
        "revision": "35eeb2e287bf19812fd58f388fe8c0bb"
    },
    {
        "url": "ms word receipt gen/barcode_generator.py",
        "revision": "a91720a1530479f5653592dce7db66e2"
    },
    {
        "url": "ms word receipt gen/items_catalog.xlsx",
        "revision": "9e772a2992c94ff13267d5b311553932"
    },
    {
        "url": "ms word receipt gen/qr_generator.py",
        "revision": "899285bf94fbd1205eb570715b0155e7"
    },
    {
        "url": "ms word receipt gen/ribbon.xml",
        "revision": "550c2110956a5e43343e70321952a9d5"
    },
    {
        "url": "ms word receipt gen/sample_logo.png",
        "revision": "93f96ae927129f59ce6320abdd76c82f"
    },
    {
        "url": "ms word receipt gen/settings.json",
        "revision": "a86285cb05096cc88d98e91a9ec5a820"
    },
    {
        "url": "ms word receipt gen/Untitled-1.md",
        "revision": "2c3820cc18ea52f7a72b0467ec26b412"
    },
    {
        "url": "ms word receipt gen/word receipt generator.py",
        "revision": "d17f720de7222557ca350e204ee3a552"
    },
    {
        "url": "ms word receipt gen/modules/clsCatalogItem.cls",
        "revision": "bc81404ea0ed3aae7214a5e05b52e32e"
    },
    {
        "url": "ms word receipt gen/modules/clsLineItem.cls",
        "revision": "76687215d88dd9035bf0144e0e7e7b89"
    },
    {
        "url": "ms word receipt gen/modules/clsReceipt.cls",
        "revision": "46b44d46040200015a22d6f2853d4810"
    },
    {
        "url": "ms word receipt gen/modules/clsSettings.cls",
        "revision": "935060b469bdfc3645777b487a9cb254"
    },
    {
        "url": "ms word receipt gen/modules/frmCatalog.frm",
        "revision": "44c61d0fee99c45b96e5ef27bbc456e8"
    },
    {
        "url": "ms word receipt gen/modules/frmCatalog.log",
        "revision": "523ae358671ad9aee3516002dba95045"
    },
    {
        "url": "ms word receipt gen/modules/frmFind.frm",
        "revision": "21ba70b41209d9c916e6389d08b8def8"
    },
    {
        "url": "ms word receipt gen/modules/frmFind.log",
        "revision": "d0604ca59f373f461c52e69a6432f657"
    },
    {
        "url": "ms word receipt gen/modules/frmNewReceipt.frm",
        "revision": "55d8854524bea5a5f4c31f8c082ae91b"
    },
    {
        "url": "ms word receipt gen/modules/frmNewReceipt.log",
        "revision": "c88057778eabea085ab110651d84558c"
    },
    {
        "url": "ms word receipt gen/modules/frmSettings.frm",
        "revision": "a2eae31526e154a755a67e565f91f282"
    },
    {
        "url": "ms word receipt gen/modules/frmSettings.log",
        "revision": "beed6fed98ba62b64236d871753483f5"
    },
    {
        "url": "ms word receipt gen/modules/modCatalog.bas",
        "revision": "1c7d1a2d0fee9a4a6e2309cf8f7ef93a"
    },
    {
        "url": "ms word receipt gen/modules/modLocalization.bas",
        "revision": "35af636eb746b548277ffeae46a058b8"
    },
    {
        "url": "ms word receipt gen/modules/modMath.bas",
        "revision": "fb4586ddfb94957da19467f4a33df053"
    },
    {
        "url": "ms word receipt gen/modules/modPDFPrint.bas",
        "revision": "1ec4266822b3eff12c0980cd891b5b5a"
    },
    {
        "url": "ms word receipt gen/modules/modQRBarcode.bas",
        "revision": "cb45f698764457394895c81693cd550e"
    },
    {
        "url": "ms word receipt gen/modules/modReceipt.bas",
        "revision": "dc72ce6f84bbe57fd5b1a08bc92aa4c3"
    },
    {
        "url": "ms word receipt gen/modules/modStartup.bas",
        "revision": "5e78a3b1e9760fa79094211b1f046466"
    },
    {
        "url": "ms word receipt gen/modules/modStorage.bas",
        "revision": "ae7517ada93de2c74074e550780b8458"
    },
    {
        "url": "ms word receipt gen/modules/modUI.bas",
        "revision": "c85884c56965760d4027c6d62dc99abd"
    },
    {
        "url": "ms word receipt gen/modules/modUtils.bas",
        "revision": "c2bdcfa5e60470bdec5a9d2fa1b49fc7"
    },
    {
        "url": "ms word receipt gen/ReceiptGenerator/ReceiptGenerator.docm",
        "revision": "a53511631ab670a26dfece224fb3e714"
    },
    {
        "url": "photos/logo_20250630171757.png",
        "revision": "d9c1a142d15554d4de4c82d5ef7ee647"
    },
    {
        "url": "photos/logo_20250630172845.png",
        "revision": "d9c1a142d15554d4de4c82d5ef7ee647"
    },
    {
        "url": "python school/.gitignore",
        "revision": "e38d980f9487cbf24aa06695a1a654db"
    },
    {
        "url": "python school/README.md",
        "revision": "ee69ef1a31e6da8303106c7c2cd5b54d"
    },
    {
        "url": "python school/requirements.txt",
        "revision": "735920bc44394e8841590feea82e4b1b"
    },
    {
        "url": "python school/media/attendance_add.gif",
        "revision": "f3c40b2b6f862b20eeaa5b712398e321"
    },
    {
        "url": "python school/media/attendance_edit_delete.gif",
        "revision": "c3995fca3422a343af73969f97cd94c8"
    },
    {
        "url": "python school/media/fees_add.gif",
        "revision": "53684ec88f08597c3d8391661af8418b"
    },
    {
        "url": "python school/media/fees_edit_delete.gif",
        "revision": "8e57397d3f209ad233bfca61bbbb4ba3"
    },
    {
        "url": "python school/media/header.png",
        "revision": "3042ceaeb222e0e4487944315efb34cf"
    },
    {
        "url": "python school/media/home_window.png",
        "revision": "c5c4430b427237bc5d9871835502ac29"
    },
    {
        "url": "python school/media/login.gif",
        "revision": "c8cc622db2dbc4febadc438667c90796"
    },
    {
        "url": "python school/media/logout.gif",
        "revision": "455085e4daa81f20f82d7823c9707662"
    },
    {
        "url": "python school/media/marks_add.gif",
        "revision": "eca82e45c1d111ea23c4e9a7f18e40d4"
    },
    {
        "url": "python school/media/marks_edit_delete.gif",
        "revision": "1ded84a809f1fd4649b75ed6ff453ff2"
    },
    {
        "url": "python school/media/reports.gif",
        "revision": "36c57c14c861dc132191803c4daa5e0f"
    },
    {
        "url": "python school/media/student_add.gif",
        "revision": "3bf527fba726544e2ff77e3b6e760e55"
    },
    {
        "url": "python school/media/student_edit_delete.gif",
        "revision": "c36bcd9a7d3d3fa0df7eb1027b768ad7"
    },
    {
        "url": "python school/schl_mgmt_app/main.py",
        "revision": "d419e4107392996689c06b2cfd6c52ea"
    },
    {
        "url": "python school/schl_mgmt_app/qt_ui/school.ui",
        "revision": "6e60f280a1ed57047543f2c9c2df0c61"
    },
    {
        "url": "python school/schl_mgmt_app/school_db/attendance.frm",
        "revision": "1166b5e831dc78845d8475784fe752bb"
    },
    {
        "url": "python school/schl_mgmt_app/school_db/attendance.ibd",
        "revision": "b4290cc54d822df0db0d4f3e40af2576"
    },
    {
        "url": "python school/schl_mgmt_app/school_db/fees.frm",
        "revision": "f6757d945ea9dd5d4d6b8b26cb277c90"
    },
    {
        "url": "python school/schl_mgmt_app/school_db/fees.ibd",
        "revision": "ec18b65e3b76d2c5e196f72fee61fd0b"
    },
    {
        "url": "python school/schl_mgmt_app/school_db/marks.frm",
        "revision": "6f34d85e6aa1395e715e180ae0313de3"
    },
    {
        "url": "python school/schl_mgmt_app/school_db/marks.ibd",
        "revision": "7df30e8afc460e0f5b88fbf474d2aa39"
    },
    {
        "url": "python school/schl_mgmt_app/school_db/student.frm",
        "revision": "4842c8c7b894aa16ef6fa02cf96afcc6"
    },
    {
        "url": "python school/schl_mgmt_app/school_db/student.ibd",
        "revision": "6de4838c7132416a12d200df647914bc"
    },
    {
        "url": "python school/schl_mgmt_app/src/attendance.png",
        "revision": "6249ff11a46e9152cbdd0d133c521dd8"
    },
    {
        "url": "python school/schl_mgmt_app/src/campus.png",
        "revision": "f951fe81cace6e33867c5e0e5481d627"
    },
    {
        "url": "python school/schl_mgmt_app/src/education.png",
        "revision": "3b3c1347f6389284110711ae769c1b19"
    },
    {
        "url": "python school/schl_mgmt_app/src/exam.png",
        "revision": "9195684aaeb45069de5482ca5736080a"
    },
    {
        "url": "python school/schl_mgmt_app/src/fees.png",
        "revision": "55f789711ac6c1866d3375651d446f0a"
    },
    {
        "url": "python school/schl_mgmt_app/src/login.png",
        "revision": "de5372bffa0fe210599ce59bcf3173f3"
    },
    {
        "url": "python school/schl_mgmt_app/src/marking.png",
        "revision": "699b7dec9db185123ff13369a39086ba"
    },
    {
        "url": "python school/schl_mgmt_app/src/maths.png",
        "revision": "0fef87711f34baf3f448e25a3519e290"
    },
    {
        "url": "python school/schl_mgmt_app/src/receipt-edit.png",
        "revision": "27501370d510124ddd2d2006ee291f26"
    },
    {
        "url": "python school/schl_mgmt_app/src/receipt.png",
        "revision": "4af82bc31f1ea29ecc17a0fa29ea6e7c"
    },
    {
        "url": "python school/schl_mgmt_app/src/reports.png",
        "revision": "c95184817d26414654cd0a0aaacc8b49"
    },
    {
        "url": "python school/schl_mgmt_app/src/SCHOOL MANAGEMENT SYSTEM.png",
        "revision": "3042ceaeb222e0e4487944315efb34cf"
    },
    {
        "url": "python school/schl_mgmt_app/src/school.png",
        "revision": "eff3485c11e0ca38065b2673ea7bc5d5"
    },
    {
        "url": "python school/schl_mgmt_app/src/student-edit.png",
        "revision": "77df3f1dd61603b9fd64370036fe8be5"
    },
    {
        "url": "python school/schl_mgmt_app/src/student.png",
        "revision": "be740ca85f1056a2075506dbfadeab8e"
    },
    {
        "url": "python school/schl_mgmt_app/src/welcome.png",
        "revision": "a7a1132556f56f7cc3e8c22840951127"
    },
    {
        "url": "python school/school_db/attendance.frm",
        "revision": "1166b5e831dc78845d8475784fe752bb"
    },
    {
        "url": "python school/school_db/attendance.ibd",
        "revision": "b4290cc54d822df0db0d4f3e40af2576"
    },
    {
        "url": "python school/school_db/fees.frm",
        "revision": "f6757d945ea9dd5d4d6b8b26cb277c90"
    },
    {
        "url": "python school/school_db/fees.ibd",
        "revision": "ec18b65e3b76d2c5e196f72fee61fd0b"
    },
    {
        "url": "python school/school_db/marks.frm",
        "revision": "6f34d85e6aa1395e715e180ae0313de3"
    },
    {
        "url": "python school/school_db/marks.ibd",
        "revision": "7df30e8afc460e0f5b88fbf474d2aa39"
    },
    {
        "url": "python school/school_db/student.frm",
        "revision": "4842c8c7b894aa16ef6fa02cf96afcc6"
    },
    {
        "url": "python school/school_db/student.ibd",
        "revision": "6de4838c7132416a12d200df647914bc"
    },
    {
        "url": "staff_photos/logo.png",
        "revision": "d9c1a142d15554d4de4c82d5ef7ee647"
    },
    {
        "url": "student_photos/ADM0541101.png",
        "revision": "2499e0fda40d2282524ddcade1625c8a"
    },
    {
        "url": "uploads/gallery/68a449a03eb42_7_Tips_to_Prepare_for_the_First_Day_of_School.png",
        "revision": "676bd95451a928a94419eb621258bb08"
    },
    {
        "url": "uploads/gallery/68a44a632d325_16424433938_f69a62d687_o.jpg",
        "revision": "8ab62ca12f28b56f8b51634f421e1238"
    },
    {
        "url": "uploads/gallery/68a44a71821b0_Pakistani-children-in-schools.jpg",
        "revision": "5e4c805010985a0fb0e7d8ad3dc80ccf"
    },
    {
        "url": "uploads/gallery/68a44ab693382_484620342_1048746340607867_4018364831364722985_n.jpg",
        "revision": "2e687c7274ca233c36c3903c96279026"
    },
    {
        "url": "uploads/gallery/68a44af61e4fe_493937000_1249364323858819_992749151734762105_n.jpg",
        "revision": "11c323e462081167e352542cf9ddd64e"
    },
    {
        "url": "yasin/chart.js",
        "revision": "187ffe7a12d1079ea1653198f9e19187"
    },
    {
        "url": "yasin/favicon.svg",
        "revision": "66bdb64e49e91dcf91a5742fbf7cb176"
    },
    {
        "url": "yasin/gschool app.exe",
        "revision": "509a397c770a1d7741245c73fcfff270"
    },
    {
        "url": "yasin/html2canvas.min.js",
        "revision": "d7530aa0b7587e627484c49fdf8f13f2"
    },
    {
        "url": "yasin/indexnewone.html",
        "revision": "883a7d818dc573d441410e6f01e022a9"
    },
    {
        "url": "yasin/jszip.min.js",
        "revision": "b5d02b3f0bf3ae026451909419df07bb"
    },
    {
        "url": "yasin/qrcode.min.js",
        "revision": "517b55d3688ce9ef1085a3d9632bcb97"
    },
    {
        "url": "yasin/school app.ahk",
        "revision": "cbc2ab8f4bf111f48e738dd6cb9ebbfd"
    }
]);

    workbox.routing.registerRoute(
        ({request}) => request.destination === 'style' || request.destination === 'script',
        new workbox.strategies.StaleWhileRevalidate({ cacheName: 'asset-cache' })
    );

    workbox.routing.registerRoute(
        ({request}) => request.destination === 'image',
        new workbox.strategies.CacheFirst({
            cacheName: 'image-cache',
            plugins: [ new workbox.expiration.ExpirationPlugin({ maxEntries: 60, maxAgeSeconds: 30 * 24 * 60 * 60 }) ],
        })
    );

    workbox.routing.setCatchHandler(async ({event}) => {
        if (event.request.destination === 'document') {
            return await caches.match('offline.html') || Response.error();
        }
        return Response.error();
    });

} else {
    console.log(`Workbox failed to load.`);
}