// Auto-generated by PWA builder script.
importScripts('https://storage.googleapis.com/workbox-cdn/releases/7.0.0/workbox-sw.js');

if (workbox) {
    console.log(`Workbox is loaded.`);
    
    self.addEventListener('message', (event) => {
      if (event.data && event.data.type === 'SKIP_WAITING') {
        console.log('Service Worker received SKIP_WAITING message, activating now.');
        self.skipWaiting();
      }
    });

    workbox.precaching.precacheAndRoute([
    {
        "url": "icon-72.png",
        "revision": "d7e2fea916659bbf271b4632f028fed5"
    },
    {
        "url": "icon-96.png",
        "revision": "f1bdf68dd999551760088eb79f5cbcba"
    },
    {
        "url": "icon-128.png",
        "revision": "1ec8980d1a4a78149a5ec7aac0a52a79"
    },
    {
        "url": "icon-144.png",
        "revision": "70839b0a9ce56b64a72ca87b9c29f139"
    },
    {
        "url": "icon-152.png",
        "revision": "24fd20976f6dc6d81b99bdecd571fced"
    },
    {
        "url": "icon-192.png",
        "revision": "286958b45be08bdc916b8e3126b2203d"
    },
    {
        "url": "icon-384.png",
        "revision": "d3d46f60ff5014f7d85d047e1c55329f"
    },
    {
        "url": "icon-512.png",
        "revision": "1a98134a086859d517de611e9e0579bc"
    },
    {
        "url": "favicon.ico",
        "revision": "7cbcf8be98d3ce63133537d07504db0f"
    },
    {
        "url": "bgc.png",
        "revision": "36106cfb750804a9cd2d0c8633cda5ae"
    },
    {
        "url": "bgc2.png",
        "revision": "deeb0127ebbc84c22d88b3a19c732c43"
    },
    {
        "url": "bgc3.png",
        "revision": "bc3b6d222ebcb740e42f754cd3250d86"
    },
    {
        "url": "bgc4.png",
        "revision": "fbb15774e784d882a7ddbbac8ac31552"
    },
    {
        "url": "bgc5.png",
        "revision": "c98f404a5b5a2d39b9337c4ddcaaff97"
    },
    {
        "url": "build pwa make html app offline and installable yasin best working re-run this for updates best for html only.py",
        "revision": "912a9d55d74613b8f4f07180d0df1fd3"
    },
    {
        "url": "chart.js",
        "revision": "187ffe7a12d1079ea1653198f9e19187"
    },
    {
        "url": "favicon.svg",
        "revision": "66bdb64e49e91dcf91a5742fbf7cb176"
    },
    {
        "url": "gschool app.exe",
        "revision": "509a397c770a1d7741245c73fcfff270"
    },
    {
        "url": "html2canvas.min.js",
        "revision": "d7530aa0b7587e627484c49fdf8f13f2"
    },
    {
        "url": "indexnewone.html",
        "revision": "77bcf7bbc29e29e9f273d9f2298accc3"
    },
    {
        "url": "jszip.min.js",
        "revision": "b5d02b3f0bf3ae026451909419df07bb"
    },
    {
        "url": "logo.png",
        "revision": "377904ca580f80b117d3430589a11d54"
    },
    {
        "url": "logo2.png",
        "revision": "377904ca580f80b117d3430589a11d54"
    },
    {
        "url": "manifest.json",
        "revision": "247a786ecf9705dc6c3c3444a1a790a1"
    },
    {
        "url": "offline.html",
        "revision": "8987c4b748db7cbdf5e4c6165507121b"
    },
    {
        "url": "qrcode.min.js",
        "revision": "517b55d3688ce9ef1085a3d9632bcb97"
    },
    {
        "url": "school app.ahk",
        "revision": "3a42b69c3c74463347ca2fa3010bc065"
    },
    {
        "url": "school app.exe",
        "revision": "b9d7297beb9643f593c67e77a5a9970a"
    },
    {
        "url": "sign.png",
        "revision": "ac675e0e6e31bb8dbb66f6e418008084"
    },
    {
        "url": "sw.js",
        "revision": "0b8afeb6c7c1bb4e6894689d73a1e362"
    }
]);

    workbox.routing.registerRoute(
        ({request}) => request.destination === 'style' || request.destination === 'script',
        new workbox.strategies.StaleWhileRevalidate({ cacheName: 'asset-cache' })
    );

    workbox.routing.registerRoute(
        ({request}) => request.destination === 'image',
        new workbox.strategies.CacheFirst({
            cacheName: 'image-cache',
            plugins: [ new workbox.expiration.ExpirationPlugin({ maxEntries: 60, maxAgeSeconds: 30 * 24 * 60 * 60 }) ],
        })
    );

    workbox.routing.setCatchHandler(async ({event}) => {
        if (event.request.destination === 'document') {
            return await caches.match('offline.html') || Response.error();
        }
        return Response.error();
    });

} else {
    console.log(`Workbox failed to load.`);
}